version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freight
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/freight
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change-me
      REFRESH_TOKEN_SECRET: change-me-too
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMS_GATEWAY_API_KEY: dummy
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: ["pnpm", "worker"]
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/freight
      REDIS_URL: redis://redis:6379
      JWT_SECRET: change-me
      REFRESH_TOKEN_SECRET: change-me-too
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMS_GATEWAY_API_KEY: dummy
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      VITE_API_BASE_URL: http://api:4000
    ports:
      - "8080:80"
    depends_on:
      - api

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
